# render.yaml ─ BiteSpeed Identity Blueprint
databases:
  - name: bitespeed-db          # free Postgres instance
    plan: free

services:
  - type: web
    name: bitespeed-api
    env: docker
    plan: free

    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeploy: true

    # Health-check hits Express /metrics
    healthCheckPath: /metrics

    envVars:
      # Inject DATABASE_URL from the database above
      - key: DATABASE_URL
        fromDatabase:
          name: bitespeed-db
          property: connectionString

      # Same defaults as .env.example
      - key: AI_URL_SIMILAR
        value: http://ai-service:8000/similar

      - key: PORT
        value: 3000

      - key: LOG_LEVEL
        value: info
